name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-package:
    name: Create and Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip addon
        run: |
          mkdir -p releases
          zip -r releases/adf_addon.zip blenderaddon

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: releases/adf_addon.zip
          tags: ${{ github.sha }}
          name: Release ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
