name: Create Release

on:
  push:
    branches:
      - release

jobs:
  create-package:
    name: Create and Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip addon
        run: |
          mkdir -p releases
          zip -r releases/adf_addon.zip blenderaddon

      - name: Verify Zip
        run: ls -l releases

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: releases/adf_addon.zip
          name: Release ${{ github.run_number }}
          tag: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
